# Generated by Django 5.2.15 on 2026-07-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datas',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
